namespace: staging

app:
  name: order-service

image:
  repository: shubhamnavale8177/order-service
  tag: v1
  pullPolicy: Always

replicaCount: 2

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: order.staging.local
  path: /api/orders

resources:
  requests:
    cpu: 200m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70