namespace: production

app:
  name: user-service

image:
  repository: shubhamnavale8177/user-service
  tag: v1
  pullPolicy: Always

replicaCount: 1

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: user.production.local
  path: /api/users

resources:
  requests:
    cpu: 50m
    memory: 64Mi

  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60