namespace: staging

app:
  name: user-service

image:
  repository: https://github.com/Shubham81772532/k8s-gitops-platform.git
  tag: v1
  pullPolicy: Always

replicaCount: 2

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: user.staging.local
  path: /api/users

resources:
  requests:
    cpu: 200m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60