namespace: production

app:
  name: payment-service

image:
  repository: shubhamnavale8177/payment-service
  tag: v1
  pullPolicy: Always

replicaCount: 3

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: payment.production.local
  path: /api/payments

resources:
  requests:
    cpu: 500m
    memory: 512Mi

  limits:
    cpu: 1
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60